INSERT INTO kitaplar (title, author, category, stock_sayisi, like_sayisi) VALUES
('Aynadaki Yalan', 'Necip Fazıl Kısakürek', 'Roman', 5, 0),
('Kafa Kağıdı', 'Necip Fazıl Kısakürek', 'Roman', 3, 0),
('Safahat', 'Mehmet Akif Ersoy', 'Roman', 10, 0),
('Çile', 'Necip Fazıl Kısakürek', 'Roman', 7, 0),
('Bir Adam Yaratmak', 'Necip Fazıl Kısakürek', 'Roman', 40, 0),
('Dokuzuncu Hariciye Koğuşu', 'Peyami Safa', 'Roman', 6, 0),
('Fatih-Harbiye', 'Peyami Safa', 'Roman', 8, 0),
('Yalnızız', 'Peyami Safa', 'Roman', 4, 0),
('Küçük Ağa', 'Tarık Buğra', 'Roman', 5, 0),
('Osmancık', 'Tarık Buğra', 'Roman', 6, 0),
('Çalıkuşu', 'Reşat Nuri Güntekin', 'Roman', 9, 0),
('Yaprak Dökümü', 'Reşat Nuri Güntekin', 'Roman', 7, 0),
('Dudaktan Kalbe', 'Reşat Nuri Güntekin', 'Roman', 5, 0),
('Huzur', 'Ahmet Hamdi Tanpınar', 'Roman', 4, 0),
('Saatleri Ayarlama Enstitüsü', 'Ahmet Hamdi Tanpınar', 'Roman', 6, 0),
('Mahur Beste', 'Ahmet Hamdi Tanpınar', 'Roman', 3, 0),
('Sinekli Bakkal', 'Halide Edip Adıvar', 'Roman', 8, 0),
('Ateşten Gömlek', 'Halide Edip Adıvar', 'Roman', 5, 0),
('Vurun Kahpeye', 'Halide Edip Adıvar', 'Roman', 6, 0),
('Yaban', 'Yakup Kadri Karaosmanoğlu', 'Roman', 7, 0),
('Kiralık Konak', 'Yakup Kadri Karaosmanoğlu', 'Roman', 5, 0),
('Sodom ve Gomore', 'Yakup Kadri Karaosmanoğlu', 'Roman', 4, 0),
('Kürk Mantolu Madonna', 'Sabahattin Ali', 'Roman', 12, 0),
('Kuyucaklı Yusuf', 'Sabahattin Ali', 'Roman', 8, 0),
('İçimizdeki Şeytan', 'Sabahattin Ali', 'Roman', 7, 0),
('Tutunamayanlar', 'Oğuz Atay', 'Roman', 5, 0),
('Tehlikeli Oyunlar', 'Oğuz Atay', 'Roman', 4, 0),
('İnce Memed 1', 'Yaşar Kemal', 'Roman', 10, 0),
('İnce Memed 2', 'Yaşar Kemal', 'Roman', 6, 0),
('Yorgun Savaşçı', 'Kemal Tahir', 'Roman', 5, 0),
('Devlet Ana', 'Kemal Tahir', 'Roman', 6, 0),
('Eylül', 'Mehmet Rauf', 'Roman', 4, 0),
('Mai ve Siyah', 'Halid Ziya Uşaklıgil', 'Roman', 5, 0),
('Aşk-ı Memnu', 'Halid Ziya Uşaklıgil', 'Roman', 6, 0),
('Sözde Kızlar', 'Peyami Safa', 'Roman', 4, 0),
('Matmazel Noraliya’nın Koltuğu', 'Peyami Safa', 'Roman', 3, 0),
('İbişin Rüyası', 'Tarık Buğra', 'Roman', 5, 0),
('Gençliğim Eyvah', 'Tarık Buğra', 'Roman', 4, 0),
('Reisim', 'Necip Fazıl Kısakürek', 'Roman', 3, 0),
('Asım', 'Mehmet Akif Ersoy', 'Roman', 5, 0),
('Araba Sevdası', 'Recaizade Mahmut Ekrem', 'Roman', 4, 0),
('Felatun Bey ile Rakım Efendi', 'Ahmet Mithat Efendi', 'Roman', 5, 0),
('Sergüzeşt', 'Samipaşazade Sezai', 'Roman', 3, 0),
('İntibah', 'Namık Kemal', 'Roman', 4, 0),
('Cezmi', 'Namık Kemal', 'Roman', 5, 0),
('Handan', 'Halide Edip Adıvar', 'Roman', 3, 0),
('Anayurt Oteli', 'Yusuf Atılgan', 'Roman', 4, 0),
('Aylak Adam', 'Yusuf Atılgan', 'Roman', 5, 0),
('Kara Kitap', 'Orhan Pamuk', 'Roman', 4, 0),
('Beyaz Kale', 'Orhan Pamuk', 'Roman', 5, 0);

INSERT INTO kitaplar (title, author, category, stock_sayisi, like_sayisi) VALUES
('Savaş ve Barış', 'Lev Tolstoy', 'Roman', 5, 845),
('Anna Karenina 1', 'Lev Tolstoy', 'Roman', 6, 82),
('Anna Karenina 2', 'Lev Tolstoy', 'Roman', 5, 63),
('Anna Karenina 3', 'Lev Tolstoy', 'Roman', 4, 50),
('Diriliş', 'Lev Tolstoy', 'Roman', 6, 430),
('Suç ve Ceza', 'Fyodor Dostoyevski', 'Roman', 12, 988),
('Karamazov Kardeşler', 'Fyodor Dostoyevski', 'Roman', 7, 856),
('Budala', 'Fyodor Dostoyevski', 'Roman', 5, 560),
('Ezilenler', 'Fyodor Dostoyevski', 'Roman', 3, 320),
('Kumarbaz', 'Fyodor Dostoyevski', 'Roman', 8, 415),
('Sefiller', 'Victor Hugo', 'Roman', 15, 940),
('Notre Dame’ın Kamburu', 'Victor Hugo', 'Roman', 6, 680),
('Madam Bovary', 'Gustave Flaubert', 'Roman', 4, 290),
('Duygusal Eğitim', 'Gustave Flaubert', 'Roman', 3, 150),
('Büyük Umutlar', 'Charles Dickens', 'Roman', 5, 520),
('İki Şehrin Hikayesi', 'Charles Dickens', 'Roman', 7, 730),
('Oliver Twist', 'Charles Dickens', 'Roman', 9, 610),
('Jane Eyre', 'Charlotte Brontë', 'Roman', 4, 480),
('Uğultulu Tepeler', 'Emily Brontë', 'Roman', 5, 590),
('Aşk ve Gurur', 'Jane Austen', 'Roman', 10, 890),
('Akıl ve Tutku', 'Jane Austen', 'Roman', 6, 340),
('Moby Dick', 'Herman Melville', 'Roman', 3, 270),
('Muhteşem Gatsby', 'F. Scott Fitzgerald', 'Roman', 8, 760),
('Gazap Üzümleri', 'John Steinbeck', 'Roman', 5, 640),
('Fareler ve İnsanlar', 'John Steinbeck', 'Roman', 11, 810),
('Yaşlı Adam ve Deniz', 'Ernest Hemingway', 'Roman', 7, 540),
('Çanlar Kimin İçin Çalıyor', 'Ernest Hemingway', 'Roman', 4, 420),
('Don Kişot', 'Miguel de Cervantes', 'Roman', 6, 670),
('Monte Kristo Kontu', 'Alexandre Dumas', 'Roman', 8, 880),
('Üç Silahşörler', 'Alexandre Dumas', 'Roman', 5, 530),
('Ulysses', 'James Joyce', 'Roman', 2, 120),
('Dava', 'Franz Kafka', 'Roman', 6, 9999),
('Dönüşüm', 'Franz Kafka', 'Roman', 14, 915),
('Şato', 'Franz Kafka', 'Roman', 3, 310),
('Yüzyıllık Yalnızlık', 'Gabriel García Márquez', 'Roman', 7, 860),
('Kolera Günlerinde Aşk', 'Gabriel García Márquez', 'Roman', 5, 490),
('Yabancı', 'Albert Camus', 'Roman', 9, 780),
('Veba', 'Albert Camus', 'Roman', 6, 620),
('Cesur Yeni Dünya', 'Aldous Huxley', 'Roman', 8, 830),
('Hayvan Çiftliği', 'George Orwell', 'Roman', 15, 995),
('Fahrenheit 451', 'Ray Bradbury', 'Roman', 10, 875),
('Dorian Gray’in Portresi', 'Oscar Wilde', 'Roman', 7, 720),
('Huckleberry Finn’in Maceraları', 'Mark Twain', 'Roman', 4, 340),
('Tom Sawyer’ın Maceraları', 'Mark Twain', 'Roman', 6, 450),
('David Copperfield', 'Charles Dickens', 'Roman', 3, 210),
('Gulliver’in Gezileri', 'Jonathan Swift', 'Roman', 5, 390),
('Robinson Crusoe', 'Daniel Defoe', 'Roman', 6, 510),
('Frankenstein', 'Mary Shelley', 'Roman', 4, 660),
('Dracula', 'Bram Stoker', 'Roman', 5, 740),
('Küçük Prens', 'Antoine de Saint-Exupéry', 'Roman', 20, 999),
('Faust', 'Goethe', 'Roman', 3, 380),
('Genç Werther’in Acıları', 'Goethe', 'Roman', 5, 460);

INSERT INTO kitaplar (title, author, category, stock_sayisi, like_sayisi) VALUES
('Leyla ile Mecnun', 'Fuzuli', 'Roman', 8, 955),
('Hüsn ü Aşk', 'Şeyh Galip', 'Roman', 5, 880),
('Hayriyye', 'Nabi', 'Roman', 4, 420),
('Hayrabad', 'Nabi', 'Roman', 3, 310),
('Harname', 'Şeyhi', 'Roman', 6, 675),
('Hüsrev ü Şirin', 'Şeyhi', 'Roman', 4, 340),
('Vesiletü’n-Necat (Mevlid)', 'Süleyman Çelebi', 'Roman', 12, 990),
('Risaletü’n-Nushiyye', 'Yunus Emre', 'Roman', 10, 920),
('Mantıku’t-Tayr', 'Gülşehri', 'Roman', 7, 580),
('Garibname', 'Aşık Paşa', 'Roman', 5, 290),
('İskendername', 'Ahmedi', 'Roman', 4, 315),
('Cemşid ü Hurşid', 'Ahmedi', 'Roman', 3, 210),
('Beng ü Bade', 'Fuzuli', 'Roman', 6, 480),
('Heft Cam', 'Fuzuli', 'Roman', 2, 150),
('Şikayetname', 'Fuzuli', 'Roman', 9, 810),
('Hadikatü’s-Süeda', 'Fuzuli', 'Roman', 5, 540),
('Rind ü Zahid', 'Fuzuli', 'Roman', 4, 370),
('Divan-ı Kebir Seçmeleri', 'Mevlana', 'Roman', 15, 998),
('Mesnevi’den Hikayeler', 'Mevlana', 'Roman', 20, 970),
('Fihi Ma Fih', 'Mevlana', 'Roman', 8, 720),
('Mecalis-i Seb’a', 'Mevlana', 'Roman', 5, 410),
('Divan', 'Baki', 'Roman', 6, 630),
('Kanuni Mersiyesi', 'Baki', 'Roman', 7, 850),
('Divan', 'Nedim', 'Roman', 9, 790),
('Lale Devri Şiirleri', 'Nedim', 'Roman', 5, 520),
('Tuhfetü’l-Harameyn', 'Nabi', 'Roman', 3, 230),
('Siham-ı Kaza', 'Nef’i', 'Roman', 6, 710),
('Divan', 'Nef’i', 'Roman', 4, 440),
('Lügat-ı Şahidi', 'Şahidi', 'Roman', 2, 180),
('Şah u Geda', 'Yahya Bey', 'Roman', 4, 320),
('Yusuf u Züleyha', 'Yahya Bey', 'Roman', 5, 610),
('Gencine-i Raz', 'Yahya Bey', 'Roman', 3, 240),
('Saki-name', 'Fuzuli', 'Roman', 5, 390),
('Mihnet-keşan', 'Keçecizade İzzet Molla', 'Roman', 4, 280),
('Gülşen-i Aşk', 'Keçecizade İzzet Molla', 'Roman', 3, 190),
('Heves-name', 'Cafer Çelebi', 'Roman', 4, 215),
('Cihannüma (Seçkiler)', 'Katip Çelebi', 'Roman', 7, 840),
('Mizanü’l-Hakk', 'Katip Çelebi', 'Roman', 6, 560),
('Keşfü’z-Zunün (Özet)', 'Katip Çelebi', 'Roman', 4, 430),
('Seyahatname (İstanbul Bölümü)', 'Evliya Çelebi', 'Roman', 18, 985),
('Divan', 'Zati', 'Roman', 3, 210),
('Şem ü Pervane', 'Zati', 'Roman', 4, 350),
('Ahmed ü Mahmud', 'Zati', 'Roman', 2, 140),
('Süheyl ü Nevbahar', 'Hoca Mesud', 'Roman', 4, 270),
('Hurşidname', 'Şeyhoğlu Mustafa', 'Roman', 3, 195),
('Marifetname (Seçkiler)', 'Erzurumlu İbrahim Hakkı', 'Roman', 10, 890),
('Müzekki’n-Nüfus', 'Eşrefoğlu Rumi', 'Roman', 6, 450),
('Divan', 'Nesimi', 'Roman', 5, 620),
('Divan', 'Kadı Burhaneddin', 'Roman', 4, 380),
('Kabusname', 'Mercimek Ahmed', 'Roman', 7, 510);

INSERT INTO kitaplar (title, author, category, stock_sayisi, like_sayisi) VALUES
('İdeolocya Örgüsü', 'Necip Fazıl Kısakürek', 'Felsefe', 5, 890),
('Batı Tefekkürü ve İslam Tasavvufu', 'Necip Fazıl Kısakürek', 'Felsefe', 3, 720),
('Çöle İnen Nur', 'Necip Fazıl Kısakürek', 'Felsefe', 7, 950),
('Devlet', 'Platon', 'Felsefe', 10, 910),
('Nikomakhos’a Etik', 'Aristoteles', 'Felsefe', 6, 640),
('Kendime Düşünceler', 'Marcus Aurelius', 'Felsefe', 15, 985),
('Böyle Buyurdu Zerdüşt', 'Friedrich Nietzsche', 'Felsefe', 8, 870),
('İyinin ve Kötünün Ötesinde', 'Friedrich Nietzsche', 'Felsefe', 5, 540),
('Saf Aklın Eleştirisi', 'Immanuel Kant', 'Felsefe', 3, 310),
('Varlık ve Hiçlik', 'Jean-Paul Sartre', 'Felsefe', 4, 425),
('Sisifos Söyleni', 'Albert Camus', 'Felsefe', 9, 780),
('Prens', 'Niccolò Machiavelli', 'Felsefe', 12, 850),
('Leviathan', 'Thomas Hobbes', 'Felsefe', 4, 290),
('Toplum Sözleşmesi', 'Jean-Jacques Rousseau', 'Felsefe', 6, 460),
('Etika', 'Baruch Spinoza', 'Felsefe', 5, 380),
('İlk Felsefe Üzerine Meditasyonlar', 'René Descartes', 'Felsefe', 7, 510),
('Yöntem Üzerine Söylev', 'René Descartes', 'Felsefe', 8, 490),
('İnsanın Anlam Arayışı', 'Viktor Frankl', 'Felsefe', 18, 995),
('İkinci Cins', 'Simone de Beauvoir', 'Felsefe', 5, 620),
('Korku ve Titreme', 'Søren Kierkegaard', 'Felsefe', 4, 340),
('Ermiş', 'Halil Cibran', 'Felsefe', 20, 990),
('Sofie’nin Dünyası', 'Jostein Gaarder', 'Felsefe', 15, 960),
('Zen ve Motosiklet Bakım Sanatı', 'Robert M. Pirsig', 'Felsefe', 6, 580),
('Özgürlük Üstüne', 'John Stuart Mill', 'Felsefe', 5, 410),
('Komünist Manifesto', 'Karl Marx', 'Felsefe', 10, 730),
('Kapital', 'Karl Marx', 'Felsefe', 3, 520),
('Candide', 'Voltaire', 'Felsefe', 7, 610),
('İtiraflar', 'Aziz Augustinus', 'Felsefe', 4, 280),
('Ben ve Sen', 'Martin Buber', 'Felsefe', 3, 190),
('İstenç ve Tasarım Olarak Dünya', 'Arthur Schopenhauer', 'Felsefe', 4, 440),
('Tractatus Logico-Philosophicus', 'Ludwig Wittgenstein', 'Felsefe', 2, 150),
('Tinin Fenomenolojisi', 'G.W.F. Hegel', 'Felsefe', 3, 310),
('Adalet Teorisi', 'John Rawls', 'Felsefe', 4, 240),
('Ölümcül Hastalık Umutsuzluk', 'Søren Kierkegaard', 'Felsefe', 5, 390),
('Düşünceler', 'Blaise Pascal', 'Felsefe', 6, 420),
('Kılavuz', 'Epiktetos', 'Felsefe', 12, 810),
('Ahlak Mektupları', 'Seneca', 'Felsefe', 14, 930),
('Yaşamın Kısalığı Üzerine', 'Seneca', 'Felsefe', 15, 945),
('Tragedyanın Doğuşu', 'Friedrich Nietzsche', 'Felsefe', 5, 370),
('Varoluşçuluk Bir Hümanizmdir', 'Jean-Paul Sartre', 'Felsefe', 8, 690),
('Açık Toplum ve Düşmanları', 'Karl Popper', 'Felsefe', 4, 315),
('Bilimsel Devrimlerin Yapısı', 'Thomas Kuhn', 'Felsefe', 5, 480),
('Şarkiyatçılık', 'Edward Said', 'Felsefe', 6, 560),
('Cinselliğin Tarihi', 'Michel Foucault', 'Felsefe', 4, 430),
('Simülakrlar ve Simülasyon', 'Jean Baudrillard', 'Felsefe', 5, 710),
('Eros ve Uygarlık', 'Herbert Marcuse', 'Felsefe', 3, 210),
('El-Medinetü’l-Fazıla', 'Farabi', 'Felsefe', 6, 680),
('Tehafütü’l-Felasife', 'Gazali', 'Felsefe', 5, 750),
('İnsan ve Kültür', 'Bozturt Güvenç', 'Felsefe', 4, 320),
('Aşk Ahlakı', 'Hilmi Ziya Ülken', 'Felsefe', 5, 415);

INSERT INTO kitaplar (title, author, category, stock_sayisi, like_sayisi) VALUES
('Clean Code: A Handbook of Agile Software Craftsmanship', 'Robert C. Martin', 'Yazılım', 10, 995),
('The Pragmatic Programmer', 'Andrew Hunt', 'Yazılım', 8, 920),
('Design Patterns: Elements of Reusable Object-Oriented Software', 'Erich Gamma', 'Yazılım', 5, 870),
('Introduction to Algorithms', 'Thomas H. Cormen', 'Yazılım', 12, 945),
('Refactoring: Improving the Design of Existing Code', 'Martin Fowler', 'Yazılım', 6, 780),
('Code Complete', 'Steve McConnell', 'Yazılım', 4, 650),
('Structure and Interpretation of Computer Programs', 'Harold Abelson', 'Yazılım', 3, 410),
('The Mythical Man-Month', 'Frederick P. Brooks Jr.', 'Yazılım', 7, 520),
('Compilers: Principles, Techniques, and Tools', 'Alfred V. Aho', 'Yazılım', 5, 390),
('Computer Networking: A Top-Down Approach', 'James Kurose', 'Yazılım', 9, 810),
('Operating System Concepts', 'Abraham Silberschatz', 'Yazılım', 6, 730),
('Modern Operating Systems', 'Andrew S. Tanenbaum', 'Yazılım', 4, 690),
('Database System Concepts', 'Silberschatz', 'Yazılım', 7, 560),
('Artificial Intelligence: A Modern Approach', 'Stuart Russell', 'Yazılım', 15, 980),
('Deep Learning', 'Ian Goodfellow', 'Yazılım', 10, 915),
('Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow', 'Aurélien Géron', 'Yazılım', 8, 890),
('Python Crash Course', 'Eric Matthes', 'Yazılım', 20, 965),
('Automate the Boring Stuff with Python', 'Al Sweigart', 'Yazılım', 18, 940),
('Effective Java', 'Joshua Bloch', 'Yazılım', 12, 880),
('Java: A Beginner\'s Guide', 'Herbert Schildt', 'Yazılım', 15, 750),
('JavaScript: The Good Parts', 'Douglas Crockford', 'Yazılım', 9, 620),
('Eloquent JavaScript', 'Marijn Haverbeke', 'Yazılım', 11, 840),
('You Don\'t Know JS Yet', 'Kyle Simpson', 'Yazılım', 7, 710),
('Cracking the Coding Interview', 'Gayle Laakmann McDowell', 'Yazılım', 25, 999),
('Soft Skills: The Software Developer\'s Life Manual', 'John Sonmez', 'Yazılım', 6, 540),
('The Clean Coder', 'Robert C. Martin', 'Yazılım', 8, 830),
('Domain-Driven Design', 'Eric Evans', 'Yazılım', 5, 470),
('Test Driven Development: By Example', 'Kent Beck', 'Yazılım', 7, 615),
('Working Effectively with Legacy Code', 'Michael Feathers', 'Yazılım', 4, 490),
('Head First Design Patterns', 'Eric Freeman', 'Yazılım', 10, 895),
('Algorithm Design Manual', 'Steven S. Skiena', 'Yazılım', 6, 760),
('Programming Pearls', 'Jon Bentley', 'Yazılım', 5, 580),
('C Programming Language', 'Brian W. Kernighan', 'Yazılım', 8, 850),
('The Art of Computer Programming', 'Donald Knuth', 'Yazılım', 3, 970),
('Site Reliability Engineering', 'Betsy Beyer', 'Yazılım', 6, 680),
('Continuous Delivery', 'Jez Humble', 'Yazılım', 5, 530),
('Building Microservices', 'Sam Newman', 'Yazılım', 7, 745),
('Kubernetes Up & Running', 'Kelsey Hightower', 'Yazılım', 9, 820),
('Docker Deep Dive', 'Nigel Poulton', 'Yazılım', 12, 860),
('Learning SQL', 'Alan Beaulieu', 'Yazılım', 15, 690),
('Clean Architecture', 'Robert C. Martin', 'Yazılım', 10, 935),
('Designing Data-Intensive Applications', 'Martin Kleppmann', 'Yazılım', 8, 990),
('Hacking: The Art of Exploitation', 'Jon Erickson', 'Yazılım', 5, 710),
('The Web Application Hacker\'s Handbook', 'Dafydd Stuttard', 'Yazılım', 4, 630),
('Linux Bible', 'Christopher Negus', 'Yazılım', 10, 780),
('C++ Primer', 'Stanley B. Lippman', 'Yazılım', 7, 590),
('Spring in Action', 'Craig Walls', 'Yazılım', 12, 925),
('Learning React', 'Alex Banks', 'Yazılım', 14, 840),
('Fullstack Vue', 'Hassan Djirdeh', 'Yazılım', 6, 410),
('Grokking Algorithms', 'Aditya Bhargava', 'Yazılım', 20, 985);